### ISSUE TITLE
The documentation for using it is a bit sketchy, and I'm not sure how to use it.

### ISSUE THREAD

**Issue by TajangSec** [AlaBouali/bane#19]
## I used this tool a long time ago when it was clearly documented as follows
![Clip_2024-07-02_17-12-26](https://github.com/AlaBouali/bane/assets/63721558/789af1b0-7230-4073-a924-407fabc19c25)
![Clip_2024-07-02_17-15-29](https://github.com/AlaBouali/bane/assets/63721558/fa38f4ea-00c9-454a-83ec-2cab978d81ac)
## But now the use of the document are turned into a link, the query is not convenient, and the operating system scanning there, I want to scan a certain IP Windows system, in the document can not find where to fill in the target IP!
![Clip_2024-07-02_17-08-29](https://github.com/AlaBouali/bane/assets/63721558/48cfb066-48dd-4a02-b57e-2ffd1e6f2d66)

**Comment by BigYashi69** [comment]
where did you find that page with all commands. i’m having trouble running ddos and i’ve figured it out to where i can ddos myself but not anybody else. lol

**Comment by AlaBouali** [comment]
@TajangSec these are you for scanning IPs / domains since it is hard to identify the OS of devices online, let alone their OS version exactly. So, this functionality alongside the ones that require no "host" / "IP" / "URL" as an argument, don't take any address, it just takes the information you give about (in your case), an OS and a specific version and then it lists all its CVE ( Common Vulnerabilities and Exposures ) based on them. If you want to scan online targets, here are what you are looking for :

https://github.com/AlaBouali/bane/tree/master/bane/bruteforce
https://github.com/AlaBouali/bane/tree/master/bane/gather_info
https://github.com/AlaBouali/bane/tree/master/bane/scanners/cms
https://github.com/AlaBouali/bane/tree/master/bane/scanners/lms
https://github.com/AlaBouali/bane/tree/master/bane/scanners/network_protocols
https://github.com/AlaBouali/bane/tree/master/bane/scanners/vulnerabilities
https://github.com/AlaBouali/bane/tree/master/bane/scanners/web_dev
https://github.com/AlaBouali/bane/tree/master/bane/utils/pager

The Bane project grew in size since the last time you've used it in terms of code base's size and architecture. in order for me to maintain its development and stability while keeping it simple to use by people, i've split its functionalities to complete OOP ( Object Oriented Programming ) where each class have its own clear purpose and utilities and they can keep grow overtime while keeping the code readable and easy to maintain. trust when i say that i never expected neither to grow to this extent nor to be used by as many people as now. so, I've made a decision to re-write the whole code in a better structure and this caused the old users to be confused, which is understandable.

The whole documentation now is so big that I had to split it into many sub-documentations for each class and its methods to facilitate its underdanting and usage with examples of how to use them. Feel free to look around and see by yourself how much is added now to bane and how much it evolved since the last time you've checked it out!

**Comment by AlaBouali** [comment]
@BigYashi69 i would recommend you checking this link:

https://github.com/AlaBouali/bane/tree/master/bane/ddos

i've removed most of the old DDoS tools to avoid being labeled as an individual who encourage unethical activities.. but the ones here are pretty good. im planning to add some new ones soon, so keep an eye on that documentation. ;) the flexibility of the classes in bane allow them to morph into many new tools while keeping the benifits of bane's optimizations like: re-ordering and arbitrary adding / removing of the headers, 20k unique user-agents generated for each time you import bane, generating random but valid values for each HTTP header used... all to confuse the firewalls and detection systems by making it near impossible to generate a fingerprint or patterns for the attacks. couple that with bane's capability to route traffic through TOR's networking and making each request exists from random exit node to avoid triggering IP blocking. this is quite the framework for you to create your own DDoS tools!

**Comment by AlaBouali** [comment]
i will let you both know that this is a free version of a personal project of mine which is more powerful and capable than this. this free version have limitations on purpose, since the advanced ones are not suppose to be free, just to show case my capabilities as a developer and cyber security expert for investors and potential clients.

**Comment by BigYashi69** [comment]
@AlaBouali is there any other website like https://pypi.org/project/bane/3.4.5/ that shows you a list of all the commands. im trying to run the code using the github but the only time ive had success with any code was when it was from https://pypi.org/project/bane/3.4.5/

**Comment by BigYashi69** [comment]
@AlaBouali you should really make a simple tut for dummies lol

**Comment by BigYashi69** [comment]
whenever i run bane.VSE_Flood('50.63.33.34',p=80,threads=100) it will boot me offline but not the intended ip? how do i fix this?

**Comment by AlaBouali** [comment]
@BigYashi69 sorry but that is not an issue with bane, it is your router's  bandwidth! your router couldn't handle bane's firepower lol i won't blame it though.. 100 threads is too much!! to put things into prospective:
1 threads fires up to 2000 - 3000 packet per second
keep in mind that with each thread , you are multiplying that number of packets. after certain limit, your router can't handle the traffic coming from you. i would recommend you get yourself a VPS. they are cheap and much better and safer than using your own computer.

**Comment by BigYashi69** [comment]
@AlaBouali just for saftey what is command to stop running bane.VSE_Flood('67.212.103.183', p=80,threads=10)

**Comment by TajangSec** [comment]
> @AlaBouali为了安全起见，停止运行 bane.VSE_Flood('67.212.103.183', p=80,threads=10)的命令是什么？

Ctrl + C
